import { Session, SessionLog, SessionStatus, LogSeverity } from './types';

const generateLogs = (sessionId: string): SessionLog[] => [
  {
    id: `log-${Math.random()}`,
    sessionId,
    timestamp: new Date().toISOString(),
    type: 'connection_connected',
    severity: 'success',
    message: 'Sessão conectada com sucesso.',
    origin: 'system',
    user: 'Sistema'
  },
  {
    id: `log-${Math.random()}`,
    sessionId,
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    type: 'sync_started',
    severity: 'info',
    message: 'Sincronização de contatos iniciada.',
    origin: 'system',
    user: 'Sistema'
  },
  {
    id: `log-${Math.random()}`,
    sessionId,
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    type: 'qr_generated',
    severity: 'info',
    message: 'Novo QR Code gerado pelo sistema.',
    origin: 'system',
    user: 'Sistema'
  }
];

export const mockSessions: Session[] = [
  {
    id: 'sess-01',
    name: 'WhatsApp Vendas',
    nickname: 'Comercial Matriz',
    channel: 'whatsapp',
    phoneNumber: '+55 11 98765-4321',
    status: 'connected',
    environment: 'production',
    createdAt: '2023-10-15T10:00:00Z',
    updatedAt: new Date().toISOString(),
    lastActivity: new Date().toISOString(),
    lastConnectedAt: new Date().toISOString(),
    reconnectCount: 12,
    failureCount: 2,
    syncCount: 450,
    responsible: 'André Silva',
    tags: ['Comercial', 'Matriz'],
    favorite: true,
    healthScore: 98,
    recentLogs: generateLogs('sess-01'),
  },
  {
    id: 'sess-02',
    name: 'WhatsApp Suporte',
    nickname: 'Atendimento N1',
    channel: 'whatsapp',
    phoneNumber: '+55 11 99999-8888',
    status: 'pairing',
    environment: 'production',
    createdAt: '2023-11-01T14:30:00Z',
    updatedAt: new Date().toISOString(),
    lastActivity: new Date().toISOString(),
    reconnectCount: 5,
    failureCount: 1,
    syncCount: 120,
    responsible: 'Carlos Oliveira',
    tags: ['Suporte', 'N1'],
    favorite: false,
    healthScore: 85,
    recentLogs: generateLogs('sess-02'),
  },
  {
    id: 'sess-03',
    name: 'WhatsApp Marketing',
    nickname: 'Envios Massa',
    channel: 'whatsapp',
    phoneNumber: '+55 11 97777-6666',
    status: 'error',
    environment: 'production',
    createdAt: '2023-09-20T08:15:00Z',
    updatedAt: new Date().toISOString(),
    lastActivity: new Date(Date.now() - 86400000).toISOString(),
    lastDisconnectedAt: new Date(Date.now() - 86400000).toISOString(),
    disconnectReason: 'QR Code expired or session terminated from device.',
    reconnectCount: 45,
    failureCount: 18,
    syncCount: 890,
    responsible: 'Beatriz Santos',
    tags: ['Marketing', 'High Volume'],
    favorite: false,
    healthScore: 42,
    recentLogs: [
      {
        id: 'err-1',
        sessionId: 'sess-03',
        timestamp: new Date().toISOString(),
        type: 'connection_error',
        severity: 'error',
        message: 'Falha crítica na conexão. Sessão invalidada no dispositivo.',
        origin: 'engine',
        user: 'Sistema'
      },
      ...generateLogs('sess-03')
    ],
  },
  {
    id: 'sess-04',
    name: 'WhatsApp RH',
    nickname: 'Recrutamento',
    channel: 'whatsapp',
    phoneNumber: '+55 11 95555-4444',
    status: 'disconnected',
    environment: 'test',
    createdAt: '2024-01-10T09:00:00Z',
    updatedAt: new Date().toISOString(),
    lastActivity: new Date(Date.now() - 172800000).toISOString(),
    reconnectCount: 2,
    failureCount: 0,
    syncCount: 15,
    responsible: 'Mariana Lima',
    tags: ['Internal', 'HR'],
    favorite: false,
    healthScore: 100,
    recentLogs: generateLogs('sess-04'),
  },
  {
    id: 'sess-05',
    name: 'WhatsApp Financeiro',
    nickname: 'Cobrança',
    channel: 'whatsapp',
    phoneNumber: '+55 11 94444-3333',
    status: 'paused',
    environment: 'production',
    createdAt: '2023-12-05T11:45:00Z',
    updatedAt: new Date().toISOString(),
    lastActivity: new Date(Date.now() - 3600000).toISOString(),
    reconnectCount: 8,
    failureCount: 1,
    syncCount: 210,
    responsible: 'Ricardo Lima',
    tags: ['Finance', 'Private'],
    favorite: true,
    healthScore: 92,
    recentLogs: generateLogs('sess-05'),
  }
];
